### ISSUE TITLE
Memory leek in jobfied version

### ISSUE THREAD

**Issue by MUN1Z** [vadersb/Unity_SpriteBatcherTest#1]
Memory leek in jobfied version, the RAM memory is increasing until it bursts.

**Comment by vadersb** [comment]
Can't replicate in the Editor and with standalone Windows build with IL2CPP backend. RAM usage remains constant.

**Comment by MUN1Z** [comment]
Sorry about that, I executed it quickly and didn't pay close attention, it takes up a little memory after execution, but after a few seconds it reaches a value where it stays fixed.

On started:
 ![image](https://github.com/vadersb/Unity_SpriteBatcherTest/assets/17263249/6f58d2ac-bab9-4e8a-bb69-f8eaa7a92ba9)
 
 few secounds ago:
 
![image](https://github.com/vadersb/Unity_SpriteBatcherTest/assets/17263249/c84f498e-e6a4-47dc-adbf-7644677f18a1)

I remember that I had tested using a much larger atlas, and it had grown more memory than that, I think that's why I opened the issue. As soon as I have time I will test again, I had stopped using your package because in my current game I cannot use an atlas sprite, so I am trying to draw the sprites in another way, because your code, the texture that represents my atlas has size 8192x8192, it is unfeasible to use this size in the atlas sprite because as it currently stands your code needs to perform the slice, this process here on my machine of performing the slice on a texture of this size takes 5 hours, in addition to taking a few hours to build the resources.

**Comment by vadersb** [comment]
Not sure the exact problem you have with atlases (are you talking about the process of Unity packing all the necessary sprites into an atlas automatically?). The thing is for sprites to be batched, they need to be related to the single texture (in other words: you can't batch sprites that use different textures). So the atlas is just a way to make sure that all the sprites share the same texture. Btw, if `SpriteBatchRenderSetup` component is provided with a single sprite, there is no requirement for that sprite to be a part of an atlas, so the sprite may use a regular texture.
